// Vocab-to-vocab relationships, curated from the actual Level C definitions.
// SYN_GROUPS: every word in a group shares a meaning with the others.
// ANT_PAIRS: the two words are opposites.
// All words below are drawn from the 300-word Level C list (validated in words.js).
const SYN_GROUPS = [
  ["invalidate", "annul", "nullify", "negate"],
  ["resolute", "steadfast"],
  ["arrogant", "haughty", "overbearing"],
  ["crucial", "pivotal", "imperative"],
  ["dire", "calamitous"],
  ["genial", "personable"],
  ["bountiful", "ample"],
  ["haggard", "gaunt"],
  ["vex", "perturb", "rankle", "exasperate", "chafe"],
  ["deface", "defile", "taint"],
  ["plunder", "ransack", "ravage"],
  ["obliterate", "pulverize"],
  ["bestow", "endow", "impart"],
  ["relevant", "pertinent", "apt"],
  ["outlandish", "exotic"],
  ["accord", "unison"],
  ["bolster", "sustain"],
  ["premonition", "foreboding", "trepidation"],
  ["tedious", "bland"],
  ["judicious", "rational"],
  ["minimize", "belittle"],
  ["doctrine", "tenet"],
  ["waver", "falter"],
  ["frivolous", "facetious"],
];

const ANT_PAIRS = [
  ["venerate", "vilify"],
  ["venerate", "belittle"],
  ["frugal", "prodigal"],
  ["forthright", "oblique"],
  ["forthright", "cryptic"],
  ["articulate", "cryptic"],
  ["dexterous", "ungainly"],
  ["accord", "enmity"],
  ["accord", "discordant"],
  ["unison", "discordant"],
  ["amplify", "minimize"],
  ["aloof", "genial"],
  ["aloof", "personable"],
  ["churlish", "genial"],
  ["churlish", "personable"],
  ["unassuming", "arrogant"],
  ["unassuming", "haughty"],
  ["unassuming", "overbearing"],
  ["fervent", "blase"],
  ["ample", "devoid"],
  ["bountiful", "devoid"],
  ["evolve", "revert"],
  ["collaborate", "vie"],
  ["instigate", "appease"],
  ["instigate", "mediate"],
  ["audacious", "skittish"],
  ["crucial", "frivolous"],
  ["pivotal", "frivolous"],
  ["nauseate", "gratify"],
  ["oblivion", "renown"],
  ["staid", "jaunty"],
  ["exotic", "conventional"],
  ["outlandish", "conventional"],
];
